version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update -y || sudo yum update -y
      - sudo apt-get install -y git || sudo yum install -y git

  pre_build:
    commands:
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Starting build process..."
      - echo "Checking if repository was cloned successfully..."
      - ls -la
      - echo "Copying files to dist directory..."
      - mkdir -p dist
      - rsync -av --exclude='dist' ./ dist/

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - dist/**
