version: 0.2

phases:
  install:
    commands:
      - echo "Authenticating with GitHub"
      - git config --global credential.helper 'store'
      - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials  # Using the new token

  build:
    commands:
      - echo "Cloning repository..."
      - git clone https://github.com/maazshaikh-tsl/AWS-codepipeline.git  # Update with your repo
      - cd AWS-codepipeline
      - mkdir -p dist
      - cp -r . dist/

artifacts:
  files:
    - dist/**

