version: 0.2

phases:
  build:
    commands:
      - zip -r application.zip . -x "*.git*"

  post_build:
    commands:
      - aws s3 cp application.zip s3://tsl-bucket-2025/

artifacts:
  files:
    - application.zip
