version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - |
        if [ -f /etc/debian_version ]; then 
          export PKG_MANAGER="apt-get"; 
        else 
          export PKG_MANAGER="yum"; 
        fi
      - echo "Using package manager: $PKG_MANAGER"
      - sudo $PKG_MANAGER update -y
      - sudo $PKG_MANAGER install -y git

      - echo "Authenticating with GitHub"
      - git config --global credential.helper 'store'
      - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials

  build:
    commands:
      - echo "Cloning repository..."
      - git clone https://github.com/maazshaikh-tsl/AWS-codepipeline.git  # Update with your actual repo URL
      - echo "Checking if repository was cloned successfully..."
      - ls -la
      - mkdir -p dist                           
      - cd AWS-codepipeline              # Navigate to the cloned repo directory
      - echo "Listing files inside the cloned repo..."
      - ls -la                           # Ensure that the repository contains files
      - chmod -R 755 .                   # Ensure files have readable permissions
      - echo "Copying files to dist directory..."
      - cp -r . ../dist/                    # Copy all files to dist/

artifacts:
  files:
    - dist/**
