version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update -y || sudo yum update -y
      - sudo apt-get install -y git || sudo yum install -y git

  build:
    commands:
      - echo "Starting build process..."
      - echo "Checking if repository was cloned successfully..."
      - ls -la
      - echo "Copying files to dist directory..."
      - mkdir -p dist
      - cp -r * dist/

artifacts:
  files:
    - dist/**
