version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - echo "Build phase: No build needed for static files."
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**'  # Store everything in the repo
