version: 0.2

phases:
  install:
    commands:
      - echo "Cleaning DNF metadata..."
      - sudo dnf clean all  # Clean expired metadata
      - sudo dnf makecache  # Rebuild cache
      - sudo dnf update -y
      - sudo dnf install -y git

  pre_build:
    commands:
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Starting build process..."
      - ls -la
      - mkdir -p scripts dist
      - rsync -av --exclude='dist' ./ dist/

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'  
