version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for HTML files."
  build:
    commands:
      - echo "Zipping files for deployment..."
      - zip -r application.zip *  # Creates a ZIP of all files
  post_build:
    commands:
      - echo "Build completed successfully."
      - ls -lah application.zip
artifacts:
  files:
    - application.zip
  discard-paths: yes
