version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo dnf update -y && sudo dnf install -y git

  pre_build:
    commands:
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Starting build process..."
      - echo "Checking if repository was cloned successfully..."
      - ls -la
      - echo "Ensuring scripts directory exists..."
      - mkdir -p scripts
      - echo "Copying files to dist directory..."
      - mkdir -p dist
      - cp -r * dist/  # Copy everything to dist except hidden files

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'  # Ensures all files, including scripts, are included
